// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bulletproofs.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	bulletproofs.proto

It has these top-level messages:
	Commitment
	ECPoint
	InnerProductProof
	RangeProof
	MultiRangeProof
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Commitment struct {
	EncValue []byte `protobuf:"bytes,1,opt,name=EncValue,proto3" json:"EncValue,omitempty"`
	Blind    []byte `protobuf:"bytes,2,opt,name=Blind,proto3" json:"Blind,omitempty"`
	X        []byte `protobuf:"bytes,3,opt,name=X,proto3" json:"X,omitempty"`
	Y        []byte `protobuf:"bytes,4,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (m *Commitment) Reset()                    { *m = Commitment{} }
func (m *Commitment) String() string            { return proto.CompactTextString(m) }
func (*Commitment) ProtoMessage()               {}
func (*Commitment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Commitment) GetEncValue() []byte {
	if m != nil {
		return m.EncValue
	}
	return nil
}

func (m *Commitment) GetBlind() []byte {
	if m != nil {
		return m.Blind
	}
	return nil
}

func (m *Commitment) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *Commitment) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type ECPoint struct {
	Compressed []byte `protobuf:"bytes,1,opt,name=Compressed,proto3" json:"Compressed,omitempty"`
}

func (m *ECPoint) Reset()                    { *m = ECPoint{} }
func (m *ECPoint) String() string            { return proto.CompactTextString(m) }
func (*ECPoint) ProtoMessage()               {}
func (*ECPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ECPoint) GetCompressed() []byte {
	if m != nil {
		return m.Compressed
	}
	return nil
}

type InnerProductProof struct {
	L []*ECPoint `protobuf:"bytes,1,rep,name=L" json:"L,omitempty"`
	R []*ECPoint `protobuf:"bytes,2,rep,name=R" json:"R,omitempty"`
	A []byte     `protobuf:"bytes,3,opt,name=A,proto3" json:"A,omitempty"`
	B []byte     `protobuf:"bytes,4,opt,name=B,proto3" json:"B,omitempty"`
}

func (m *InnerProductProof) Reset()                    { *m = InnerProductProof{} }
func (m *InnerProductProof) String() string            { return proto.CompactTextString(m) }
func (*InnerProductProof) ProtoMessage()               {}
func (*InnerProductProof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InnerProductProof) GetL() []*ECPoint {
	if m != nil {
		return m.L
	}
	return nil
}

func (m *InnerProductProof) GetR() []*ECPoint {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *InnerProductProof) GetA() []byte {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *InnerProductProof) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

type RangeProof struct {
	A   *ECPoint           `protobuf:"bytes,2,opt,name=A" json:"A,omitempty"`
	S   *ECPoint           `protobuf:"bytes,3,opt,name=S" json:"S,omitempty"`
	T1  *ECPoint           `protobuf:"bytes,4,opt,name=T1" json:"T1,omitempty"`
	T2  *ECPoint           `protobuf:"bytes,5,opt,name=T2" json:"T2,omitempty"`
	Tau []byte             `protobuf:"bytes,6,opt,name=Tau,proto3" json:"Tau,omitempty"`
	Th  []byte             `protobuf:"bytes,7,opt,name=Th,proto3" json:"Th,omitempty"`
	Mu  []byte             `protobuf:"bytes,8,opt,name=Mu,proto3" json:"Mu,omitempty"`
	IPP *InnerProductProof `protobuf:"bytes,9,opt,name=IPP" json:"IPP,omitempty"`
}

func (m *RangeProof) Reset()                    { *m = RangeProof{} }
func (m *RangeProof) String() string            { return proto.CompactTextString(m) }
func (*RangeProof) ProtoMessage()               {}
func (*RangeProof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RangeProof) GetA() *ECPoint {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *RangeProof) GetS() *ECPoint {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *RangeProof) GetT1() *ECPoint {
	if m != nil {
		return m.T1
	}
	return nil
}

func (m *RangeProof) GetT2() *ECPoint {
	if m != nil {
		return m.T2
	}
	return nil
}

func (m *RangeProof) GetTau() []byte {
	if m != nil {
		return m.Tau
	}
	return nil
}

func (m *RangeProof) GetTh() []byte {
	if m != nil {
		return m.Th
	}
	return nil
}

func (m *RangeProof) GetMu() []byte {
	if m != nil {
		return m.Mu
	}
	return nil
}

func (m *RangeProof) GetIPP() *InnerProductProof {
	if m != nil {
		return m.IPP
	}
	return nil
}

type MultiRangeProof struct {
	A   *ECPoint           `protobuf:"bytes,2,opt,name=A" json:"A,omitempty"`
	S   *ECPoint           `protobuf:"bytes,3,opt,name=S" json:"S,omitempty"`
	T1  *ECPoint           `protobuf:"bytes,4,opt,name=T1" json:"T1,omitempty"`
	T2  *ECPoint           `protobuf:"bytes,5,opt,name=T2" json:"T2,omitempty"`
	Tau []byte             `protobuf:"bytes,8,opt,name=Tau,proto3" json:"Tau,omitempty"`
	Th  []byte             `protobuf:"bytes,9,opt,name=Th,proto3" json:"Th,omitempty"`
	Mu  []byte             `protobuf:"bytes,10,opt,name=Mu,proto3" json:"Mu,omitempty"`
	IPP *InnerProductProof `protobuf:"bytes,11,opt,name=IPP" json:"IPP,omitempty"`
}

func (m *MultiRangeProof) Reset()                    { *m = MultiRangeProof{} }
func (m *MultiRangeProof) String() string            { return proto.CompactTextString(m) }
func (*MultiRangeProof) ProtoMessage()               {}
func (*MultiRangeProof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MultiRangeProof) GetA() *ECPoint {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *MultiRangeProof) GetS() *ECPoint {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *MultiRangeProof) GetT1() *ECPoint {
	if m != nil {
		return m.T1
	}
	return nil
}

func (m *MultiRangeProof) GetT2() *ECPoint {
	if m != nil {
		return m.T2
	}
	return nil
}

func (m *MultiRangeProof) GetTau() []byte {
	if m != nil {
		return m.Tau
	}
	return nil
}

func (m *MultiRangeProof) GetTh() []byte {
	if m != nil {
		return m.Th
	}
	return nil
}

func (m *MultiRangeProof) GetMu() []byte {
	if m != nil {
		return m.Mu
	}
	return nil
}

func (m *MultiRangeProof) GetIPP() *InnerProductProof {
	if m != nil {
		return m.IPP
	}
	return nil
}

func init() {
	proto.RegisterType((*Commitment)(nil), "pb.Commitment")
	proto.RegisterType((*ECPoint)(nil), "pb.ECPoint")
	proto.RegisterType((*InnerProductProof)(nil), "pb.InnerProductProof")
	proto.RegisterType((*RangeProof)(nil), "pb.RangeProof")
	proto.RegisterType((*MultiRangeProof)(nil), "pb.MultiRangeProof")
}

func init() { proto.RegisterFile("bulletproofs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0x5f, 0x6b, 0xf2, 0x30,
	0x18, 0xc5, 0x49, 0xfa, 0xfa, 0xef, 0x51, 0xde, 0x6d, 0x61, 0x83, 0x6c, 0x83, 0x21, 0xbd, 0x99,
	0xbb, 0x11, 0x74, 0x9f, 0xa0, 0x8a, 0x17, 0x82, 0x42, 0x89, 0x65, 0xe8, 0xee, 0xac, 0xcd, 0x66,
	0xa1, 0x4d, 0x4a, 0x9b, 0x7c, 0xd6, 0xdd, 0xec, 0xc3, 0x8c, 0xa4, 0x2a, 0x23, 0x13, 0x76, 0xb9,
	0xbb, 0x9c, 0xe7, 0x17, 0xce, 0x73, 0x4e, 0x08, 0x90, 0x58, 0x67, 0x19, 0x57, 0x45, 0x29, 0xe5,
	0x5b, 0x35, 0x2c, 0x4a, 0xa9, 0x24, 0xc1, 0x45, 0xec, 0xbf, 0x02, 0x4c, 0x65, 0x9e, 0xa7, 0x2a,
	0xe7, 0x42, 0x91, 0x3b, 0x68, 0xcf, 0xc4, 0xee, 0x65, 0x9b, 0x69, 0x4e, 0x51, 0x1f, 0x0d, 0x7a,
	0xec, 0xa4, 0xc9, 0x35, 0x34, 0x26, 0x59, 0x2a, 0x12, 0x8a, 0x2d, 0xa8, 0x05, 0xe9, 0x01, 0x5a,
	0x53, 0xcf, 0x4e, 0xd0, 0xda, 0xa8, 0x0d, 0xfd, 0x57, 0xab, 0x8d, 0xff, 0x04, 0xad, 0xd9, 0x34,
	0x94, 0xa9, 0x50, 0xe4, 0xc1, 0xae, 0x29, 0x4a, 0x5e, 0x55, 0x3c, 0x39, 0x58, 0x7f, 0x9b, 0xf8,
	0x1c, 0xae, 0xe6, 0x42, 0xf0, 0x32, 0x2c, 0x65, 0xa2, 0x77, 0x2a, 0x34, 0x31, 0xc9, 0x2d, 0xa0,
	0x05, 0x45, 0x7d, 0x6f, 0xd0, 0x1d, 0x77, 0x87, 0x45, 0x3c, 0x3c, 0x98, 0x31, 0xb4, 0x30, 0x88,
	0x51, 0x7c, 0x06, 0x31, 0x93, 0x21, 0x38, 0x26, 0x0a, 0x8c, 0x9a, 0x1c, 0x13, 0x4d, 0xfc, 0x0f,
	0x04, 0xc0, 0xb6, 0xe2, 0x9d, 0x9f, 0x16, 0x04, 0xb6, 0x8e, 0xeb, 0x12, 0x18, 0xb4, 0xb2, 0x2e,
	0x2e, 0x5a, 0x91, 0x7b, 0xc0, 0xd1, 0xc8, 0x7a, 0x3a, 0x0c, 0x47, 0x23, 0x0b, 0xc7, 0xb4, 0x71,
	0x0e, 0x8e, 0xc9, 0x25, 0x78, 0xd1, 0x56, 0xd3, 0xa6, 0x8d, 0x63, 0x8e, 0xe4, 0x3f, 0xe0, 0x68,
	0x4f, 0x5b, 0x76, 0x80, 0xa3, 0xbd, 0xd1, 0x4b, 0x4d, 0xdb, 0xb5, 0x5e, 0x6a, 0xf2, 0x08, 0xde,
	0x3c, 0x0c, 0x69, 0xc7, 0xfa, 0xdd, 0x18, 0xbf, 0x1f, 0xcf, 0xc4, 0xcc, 0x0d, 0xff, 0x13, 0xc1,
	0xc5, 0x52, 0x67, 0x2a, 0xfd, 0xfb, 0x7a, 0x6d, 0xb7, 0x5e, 0xc7, 0xa9, 0x07, 0x6e, 0xbd, 0xee,
	0x6f, 0xf5, 0xe2, 0xa6, 0xfd, 0xb1, 0xcf, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x65, 0x0f,
	0x2c, 0xc7, 0x02, 0x00, 0x00,
}
